const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpg',
      desc: `Pancakes with butter, syrup, milk, and juice drink. Good for breakfast.`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: './images/item-2.jpg',
      desc: `Double patty with cheese and ham accompanied with a side of fries and nestea drink. Good for lunch.`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpg',
      desc: `Chocolate shake with chocolate chip cookie, chocolate sprinkles, and mini chocolate bars. Good for dessert.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpg',
      desc: `Chicken nuggets and omelette with juice drink. Good for breakfast.`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpg',
      desc: `Burger with egg, tomatoes, mayonaise, lettuce, and ham. Good for lunch.`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpg',
      desc: `Milkshake with crushed oreos and chocolate chips. Good for dessert.`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpg',
      desc: `Burger with cheese, bacon, patty, and mayonaise with extra side bacon and nestea. Good for breakfast.`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpg',
      desc: `Classis american bruger with lettuce, cheese, patty, tomatoes, and mayoanise with a side of fries. Good for lunch.`,
    },
    {
      id: 9,
      title: 'Buddy Ice Cream Shake',
      category: 'shakes',
      price: 16.99,
      img: './images/item-9.jpg',
      desc: `Buddy ice cream shake with side chocolate wafer bars. Good for dessert`,
    },
  ];
  export default menu;